# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rishab/Documents/ECE_385_Final_Project/DoodleJump/DoodleJump.srcs/sources_1/ip/doodle_left_t_rom_5/doodle_left_t_rom.xci
# IP: The module: 'doodle_left_t_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rishab/Documents/ECE_385_Final_Project/DoodleJump/DoodleJump.gen/sources_1/ip/doodle_left_t_rom_5/doodle_left_t_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'doodle_left_t_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/rishab/Documents/ECE_385_Final_Project/DoodleJump/DoodleJump.srcs/sources_1/ip/doodle_left_t_rom_5/doodle_left_t_rom.xci
# IP: The module: 'doodle_left_t_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rishab/Documents/ECE_385_Final_Project/DoodleJump/DoodleJump.gen/sources_1/ip/doodle_left_t_rom_5/doodle_left_t_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'doodle_left_t_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
